#!/bin/bash
class=
method=
property=
prev=
current=$1
shift
(($#)) && value="$@" || value=""
final=false
while true; do
    prev=${current%%.*}
    next=${current##*$prev.}
    [ "$prev" = "$next" ] && final=true
    current=$next
    if [ -z "$class" ]; then
        class="$prev"
    elif [ -z "$method" ]; then
        method=".$prev"
    elif [ -z "$property" ]; then
        property=".$prev"
    else
        echo "Unknown field $prev"
        break
    fi
    $final && break
done

plugins=$(dirname `realpath $0`)/plugins
for s in `find $plugins/openstack.d -type f`; do . $s; done

if [ -z "$method" ]; then
    echo -e "Choose one of the following:\n"
    declare -f| sed -rn 's/^(openstack\..+)\s+\(\).*/\1/p'
else
    eval ${class}${method}${property} $value
fi

