#!/bin/bash
openstack.local-vlans.info ()
{
    readlink $RESULTS_PATH_HOST/ovs/bridges/br-int/ports/*/vlan| xargs -l basename| sort -un    
}
# default
openstack.local-vlans ()
{
    # these are the neutron "internal" vlans used to identify tenant overlay networks
    openstack.local-vlans.info $@
}


openstack.ports.list ()
{
    local vlan=${1:-""}

    if [ -z "$vlan" ]; then
         ls $RESULTS_PATH_HOST/ovs/ports
    else
        path=$RESULTS_PATH_HOST/ovs/vlans/$vlan
        if ! [ -d "$path" ]; then
            echo "INFO: vlan $vlan not found" 1>&2
            return
        fi
        ls $path/ports
    fi
}
# default
openstack.ports ()
{
    openstack.ports.list $@
}

openstack.port.list ()
{
    # alias of
    openstack.ports $@
}
openstack.port.info ()
{
    (($#)) || { plugin_usage "name|mac address"; return; }
    local id_key=$1
    local vlan=
    local mac=
    local bridge="unknown"
    local namespace=

    port=`_find_port $id_key` || return 0
    name=`basename $port`

    mac=`cat $port/hwaddr`
    if [ -e "$port/vlan" ]; then
        vlan=`readlink $port/vlan| xargs basename`
    fi
    if [ -e "$port/namespace" ]; then
        namespace=`readlink $port/namespace| xargs basename`
    fi
    of_id=`cat $port/id`
    bridge=`readlink $port/bridge| xargs basename`
    echo "Port $name:"
    echo "  - bridge: $bridge"
    echo "  - id: $of_id"
    echo "  - local-vlan: $vlan"
    echo "  - mac address: $mac"
    [ -z "$namespace" ] || echo "  - namespace: $namespace"
}
openstack.port.flows ()
{
    (($#)) || { plugin_usage "name|mac address [table]"; return; }
    local id_key=$1
    local table=
    (($#>1)) && table=$2

    port=`_find_port $id_key` || return 0

    if [ -n "$table" ]; then
        cat $port/flows/by-table/$table
        return
    fi

    echo -e "$port/flows/all\n"
    cat $port/flows/all
    [ -s "$port/flows/all" ] && echo ""

    tree $port/flows/by-proto
    tree $port/flows/by-table
}
# default
openstack.port ()
{
    openstack.port.info $@
}

openstack.bridge.ports ()
{
    local bridge=${1:-}
    local limit=${2:-0}

    ((limit<=`ls $RESULTS_PATH_HOST/ovs/bridges| wc -l`)) || exit

    if [ -z "$bridge" ]; then
        for bridge in `ls $RESULTS_PATH_HOST/ovs/bridges`; do
            echo "$bridge:"
            openstack.bridge.ports $bridge $((limit+=1))
            echo
        done
    else
        path=$RESULTS_PATH_HOST/ovs/bridges/$bridge
        if ! [ -d "$path" ]; then
            echo "INFO: bridge $bridge not found" 1>&2
            return
        fi
        if ((`ls $path/ports/| wc -l`)); then
            readlink $path/ports/*| xargs -l basename| column
        fi
    fi
}
# default
openstack.bridge ()
{
    openstack.bridge.ports $@
}

openstack.bridges.list ()
{
    ls $RESULTS_PATH_HOST/ovs/bridges
}
# default
openstack.bridges ()
{
    openstack.bridges.list $@
}
