#!/bin/bash
get_ovs_bridge_port ()
{
    # returns translate bridge port id to port name
    local bridge=$1
    local port=$2

    [ -e "$RESULTS_PATH_HOST/ovs/bridges/$bridge/ports/$port" ] || return
    readlink -f $RESULTS_PATH_HOST/ovs/bridges/$bridge/ports/$port| \
        xargs -l basename
}
