name: ovs-stat 
version: '1.0'
summary: Tool to create a sysfs-style representation of an Openvswitch switch.
description:
    Analysing Openvswitch flow tables can be hard. This tool organises information from
    an Openvswitch switch such as flows and ports into a filesystem structure so that
    conventional tools like find, ls and grep can be used to perform queries and provide
    a more intuitive visualisation of the configuration of an ovs switch.
confinement: classic 
grade: devel 

apps:
  ovs-stat:
    command: ovs-stat.sh
    plugs: [home, removable-media]
parts:
  ovs-stat:
    source: .
    plugin: dump
    stage-packages: [coreutils, bsdmainutils, tree]

