name: ovs-stat 
version: '1.1'
summary: Tool to create a sysfs-style representation of an Openvswitch switch.
description:
    Analysing Openvswitch flow tables can be hard. This tool organises information from
    an Openvswitch switch such as flows and ports into a filesystem structure so that
    conventional tools like find, ls and grep can be used to perform queries and provide
    a more intuitive visualisation of the configuration of an ovs switch.
confinement: strict 
grade: stable
base: core18
environment:
  TMPDIR: $SNAP_COMMON/tmp

apps:
  ovs-stat:
    command: ovs-stat.sh
    plugs: [home, removable-media, network-control, openvswitch]
parts:
  ovs-stat:
    source: .
    plugin: dump
    stage-packages: [coreutils, bsdmainutils, tree, openvswitch-switch, jq, conntrack]
